services:
  - type: web
    name: letsmeet-backend
    env: node
    buildCommand: |
      npm install
      cd frontend && npm install
      cd frontend && npm run build
      cd .. && mkdir -p public && cp -r frontend/build/* public/
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5001
    healthCheckPath: /api/socket
    autoDeploy: true 