services:
  - type: web
    name: letsmeet-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 